### ISSUE TITLE
Parameter drop_rate_columns confusing

### ISSUE THREAD

**Issue by mffrank** [mffrank/scNMT_tools#1]
Should we maybe rename drop_rate_columns to drop_read_columns? We are keeping the rate column and not dropping it

**Comment by snajder-r** [comment]
Yes, you are right. In my head, the two columns that were dropped "rates" and the third column was a ratio of those rates, but of course that terminology is nonesense.  Fixed in cd718891ee447afbe2c2c25dc0fb5624b394b16e
